@startuml

!startsub InitialQualifierState
namespace score::config_management::config_provider {
enum InitialQualifierState {
    kUndefined,
    kInProgress,
    kDefault,
    kQualifying,
    kUnqualified,
    kQualified
}
}
!endsub

!startsub InitialQualifierState
namespace score::config_management::config_provider {
enum InitialQualifierState {
    kUndefined,
    kInProgress,
    kDefault,
    kQualifying,
    kUnqualified,
    kQualified
}
}
!endsub

@enduml
